#!/bin/bash

output=$(getprop | grep thermal-engine)

if [[ $output == *"[stopped]"* ]]; then
    su -c "start thermal-engine"
    getprop | grep thermal-engine
else
    su -c "stop thermal-engine"
    getprop | grep thermal-engine
fi
